sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t belendor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true belendor/react-test npm test 

after_success:
  - docker build -t belendor/multi-client ./client
  - docker build -t belendor/multi-nginx ./nginx
  - docker build -t belendor/multi-server ./server
  - docker build -t belendor/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  
  - docker push belendor/multi-client
  - docker push belendor/multi-nginx
  - docker push belendor/multi-server
  - docker push belendor/multi-worker